name: Test Entra (Service Principal) Connection
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login with SP
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get access token for Azure SQL
        id: token
        run: |
          TOKEN=$(az account get-access-token \
            --resource https://database.windows.net/ \
            --query accessToken -o tsv)
          if [ -z "$TOKEN" ]; then echo "No token"; exit 1; fi
          echo "TOKEN=$TOKEN" >> $GITHUB_OUTPUT

      - name: Install sqlpackage
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          wget -q https://aka.ms/sqlpackage-linux
          unzip -q sqlpackage-linux -d sqlpackage
          sudo chmod +x sqlpackage/sqlpackage
          echo "$GITHUB_WORKSPACE/sqlpackage" >> $GITHUB_PATH

      - name: Try connecting with token (DriftReport = no changes)
        run: |
          sqlpackage /Action:DriftReport \
            /TargetServerName:"server-ng.database.windows.net" \
            /TargetDatabaseName:"DB_NG" \
            /AccessToken:"${{ steps.token.outputs.TOKEN }}"
